### ISSUE TITLE
Parser throws error when parsing files with escape characters (\") in tags

### ISSUE THREAD

**Issue by coffeeDev98** [mliebelt/pgn-parser#309] opened 2022-11-02 06:31 UTC
Hey @mliebelt ,

Was loading this particular PGN from Lichess and noticed that pgn-parser fails throwing an error. Unsure on whether this is a grammar file issue.... I think escape characters are causing pgn-parser to throw an error.

This is the PGN
```
[Event "Bg7 in the Sicilian: 2.Nf3 d6 3.Bc4 - The \"Closed\" Dragon"]
[Site "https://lichess.org/study/iELlTRpu/nvRsm5hy"]
[Date "????.??.??"]
[White "Hyperaccelerated Dragon #4"]
[Black "1. e4 c5 2. Nf3 g6"]
[Result "*"]
[Annotator "https://lichess.org/@/fuxia"]
[UTCDate "2022.10.28"]
[UTCTime "12:58:42"]
[Variant "Standard"]
[ECO "B50"]
[Opening "Sicilian Defense: Modern Variations"]

1. e4 c5 2. Nf3 d6 { Black wants to play a Dragon. Or maybe even a Najdorf. But White goes for
a sideline: } 3. Bc4 { This has no name, but it is played even at the top level. In most cases, Black will gain a lot of space on the queen side in this line. } { [%cal Rf3g5,Rg5f7,Rc4f7,Gb7b5,Ga7a5] } 3... Nf6 { Black should just develop normally. } 4. d3 { White is still playing a Bishop's Opening. But, since Black hasn't
committed to e5, e6 is still an option } (4. Ng5?! e6 { Here Black doesn't go for a fianchetto setup. })  (4. e5 dxe5 5. Nxe5 e6 6. Qe2 { Protecting the knight against the following move: } { [%cal Re2e5] } 6... Bd6 { [%cal Gd6e5,Re2e5] } 7. O-O O-O) 4... Nc6 { No e5 for White now. } { [%csl Ge5][%cal Gc6e5,Gd6e5] } 5. c3 (5. Ng5 e6) 5... g6 (5... Na5?! 6. Bb5+) 6. O-O (6. Ng5?! { This doesn't work. } 6... e6 7. f4 d5! 8. Bb3 h6 9. Nf3 dxe4 10. dxe4 Qxd1+ { And this is why c3 was a useful move: } 11. Bxd1 Nxe4! { Black wins a pawn. } 12. O-O Bg7 $15) 6... Bg7 7. Bb3 (7. Re1 O-O 8. Bb3 b5) 7... O-O 8. Re1 (8. h3 b5 9. Re1 (9. d4)) 8... b5 9. h3 a5 10. a3 a4 11. Bc2 Nd7 $10 { [%csl Gd4][%cal Gc5d4,Gg7d4,Gc6d4] } 12. d4 *
```

The ```\"``` is what is causing the issue

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/63295908/199399701-904a45bd-ee68-4802-ba3b-a6fa274b858a.png">

**Comment by mliebelt** [comment] 2022-11-02 12:01
You were right. See the [documentation](https://github.com/mliebelt/pgn-spec-commented/blob/main/pgn-specification.md#7-tokens) where quoting is explicitly mentioned. I have to adjust the grammar for that.

**Comment by coffeeDev98** [comment] 2022-11-03 09:23
This seems to be the right implementation of the fix from the link you suggested. Tested it with a test PGN from Lichess(same as above). 

Shall I create a PR so that you can check this out and make any additional changes (variable names may not be proper). New to Peggy so, may not be the correct way to implement the fix.

These are the changes to the peggy file
<img width="992" alt="image" src="https://user-images.githubusercontent.com/63295908/199684902-295b3c3c-70e7-4f9f-827e-f39252e69088.png">

**Comment by mliebelt** [comment] 2022-11-03 09:28
Doing a pull request would be great. I will check that one, and see if this fixes our problem, and has no other problems then. Having a pull request makes my job easier, and hopefully I will do that then soon and provide a new version (including a new version for the viewer as well).

**Comment by coffeeDev98** [comment] 2022-11-03 09:32
Great! Created a PR with the above change. #310

**Comment by mliebelt** [comment] 2022-11-05 15:55
I think I fixed the problem, will doublecheck again, and then create new version out of it. The strange thing here is, that when the content comes from the outside (e.g. by calling the command line), it works with a single backslash character. However, in unit tests you have to escape the backslashes by having each one 2 times.

Tried the following on the command line (after having locally built a new version in the cloned repo)
`echo '[Event "Bg7 in the Sicilian: 2.Nf3 d6 3.Bc4 - The \"Closed\" Dragon"]*' | node ./bin/pgn-to-json.js -
[{"tags":{"Event":"Bg7 in the Sicilian: 2.Nf3 d6 3.Bc4 - The \"Closed\" Dragon","messages":[],"Result":"*"},"gameComment":null,"moves":[],"messages":[]}]`

**Comment by mliebelt** [comment] 2022-11-05 16:31
I published now all new versions:

* pgn-parser: 1.4.5
* pgn-reader: 1.2.14
* pgn-viewer: 1.6.1

Please give it a try, and give feedback, so we know if the issue is fixed now.

**Comment by coffeeDev98** [comment] 2022-11-07 06:50
Hey @mliebelt , Sorry for the delayed response.
Yes, the issue is resolved.

**Closed** 2022-11-07 07:50 UTC
